SELECT * FROM PENALTIES;
SELECT * FROM PLAYERS;
SELECT * FROM TEAMS;
SELECT * FROM MATCHES;
SELECT * FROM committee_members;

#HW3A
SELECT		COUNT(*), MAX(AMOUNT)
FROM		PENALTIES
;

#HW3B
SELECT 		PLAYERNO,
			(SELECT 	MAX(AMOUNT)
             FROM		PENALTIES
             WHERE		PENALTIES.PLAYERNO = 
						PLAYERS.PLAYERNO) - 
			(SELECT		MIN(AMOUNT)
             FROM		PENALTIES
             WHERE		PENALTIES.PLAYERNO = 
						PLAYERS.PLAYERNO) AS DIFFERENCE
FROM		PLAYERS
;

#HW3C
SELECT		TEAMNO, COUNT(*), SUM(WON)
FROM 		MATCHES
WHERE 		TEAMNO IN
			(SELECT TEAMNO
			 FROM 	TEAMS
			 WHERE 	DIVISION = 'first')
GROUP BY TEAMNO
;

#HW3D
SELECT		NAME, INITIALS
FROM		PLAYERS
WHERE		PLAYERNO IN
			(SELECT 	PLAYERNO
             FROM 		PENALTIES
             WHERE		AMOUNT > 40
             GROUP BY	PLAYERNO
             HAVING		COUNT(*) >= 2) 
;

(SELECT		MATCHNO
 FROM		MATCHES
 ORDER BY	MATCHNO ASC
 LIMIT		2)
 UNION
 (SELECT	MATCHNO
  FROM		MATCHES
  ORDER BY	MATCHNO DESC
  LIMIT		2)