USE TENNIS;

#HW2-A
SELECT 		TEAMNO
FROM 		TEAMS
WHERE 		PLAYERNO =
			(SELECT		PLAYERNO
			 FROM 		PLAYERS
			 WHERE		NAME = 'Parmenter'
			 AND		INITIALS = 'R')
;
SELECT * FROM TEAMS;
SELECT * FROM PLAYERS;
SELECT * FROM committee_members;

#HW2B									
SELECT		PAYMENTNO, PENALTIES.PLAYERNO, AMOUNT, NAME
FROM		PENALTIES, PLAYERS
WHERE		PENALTIES.PLAYERNO = PLAYERS.PLAYERNO
;

#HW2C
SELECT 		P.PLAYERNO, M.TEAMNO
FROM		PLAYERS	AS	P LEFT JOIN MATCHES AS M
			ON P.PLAYERNO = M.PLAYERNO
;
SELECT 		DISTINCT P.PLAYERNO, M.TEAMNO
FROM		PLAYERS	AS	P LEFT JOIN MATCHES AS M
			ON P.PLAYERNO = M.PLAYERNO
;

#HW2D
SELECT		DISTINCT PLAYERNO
FROM		MATCHES
WHERE		WON > LOST
;

SELECT * FROM MATCHES;

#HW2E
SELECT		PAYMENTNO
FROM		PENALTIES
WHERE		1965 <
			(SELECT	YEAR(BIRTH_DATE)
             FROM	PLAYERS
			 WHERE	PLAYERS.PLAYERNO = PENALTIES.PLAYERNO)
;


