use tennis;
SELECT * FROM PLAYERS;
SELECT * FROM penalties;
SELECT * FROM teams;
SELECT * FROM matches;
SELECT * FROM committee_members;

#HW4A
INSERT INTO 	PENALTIES
VALUES (11, 44, '1985-11-08', 100)
;
#HW4B
UPDATE 	PENALTIES
SET 	AMOUNT = AMOUNT * 2
;
#HWC
DELETE
FROM 		PENALTIES
ORDER BY 	AMOUNT ASC, PLAYERNO DESC
LIMIT 		2
;
#HW4D
DELETE
FROM 	PLAYERS
WHERE	TOWN =
		(SELECT TOWN
         FROM	PLAYERS
         WHERE	PLAYERNO = 57)
AND		PLAYERNO <> 57
;
#HW4E
DELETE	PEN, M
FROM	PENALTIES AS PEN, MATCHES AS M
WHERE	PEN.PLAYERNO = 104
AND		M.PLAYERNO = 104
;



